# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '5.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import *
import os
import mail
import mod
import veri_tabani
veriler=veri_tabani.database()
os.chdir("C:/Users/omerm/OneDrive/Masaüstü")
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1105, 846)
        Form.setWindowIcon(QtGui.QIcon("2.jpg"))
        Form.setWindowTitle("Diyabet Projesi")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(-30, 0, 1121, 851))
        self.textBrowser.setObjectName("textBrowser")
        self.surname = QtWidgets.QLineEdit(Form)
        self.surname.setGeometry(QtCore.QRect(170, 270, 211, 41))
        self.surname.setObjectName("surname")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(490, 340, 141, 71))
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(490, 460, 121, 41))
        self.label_10.setObjectName("label_10")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(490, 520, 141, 111))
        self.label_8.setObjectName("label_8")
        self.insulin = QtWidgets.QLineEdit(Form)
        self.insulin.setGeometry(QtCore.QRect(650, 180, 241, 41))
        self.insulin.setText("")
        self.insulin.setObjectName("insulin")
        self.glucose = QtWidgets.QLineEdit(Form)
        self.glucose.setGeometry(QtCore.QRect(170, 440, 211, 41))
        self.glucose.setObjectName("glucose")
        self.blood_pressure = QtWidgets.QLineEdit(Form)
        self.blood_pressure.setGeometry(QtCore.QRect(170, 530, 211, 41))
        self.blood_pressure.setObjectName("blood_pressure")
        self.age = QtWidgets.QLineEdit(Form)
        self.age.setGeometry(QtCore.QRect(650, 440, 241, 41))
        self.age.setObjectName("age")
        self.skin_thickness = QtWidgets.QLineEdit(Form)
        self.skin_thickness.setGeometry(QtCore.QRect(650, 360, 241, 41))
        self.skin_thickness.setObjectName("skin_thickness")
        self.name_2 = QtWidgets.QLineEdit(Form)
        self.name_2.setGeometry(QtCore.QRect(170, 180, 211, 41))
        self.name_2.setText("")
        self.name_2.setObjectName("name_2")
        self.pregnancie = QtWidgets.QLineEdit(Form)
        self.pregnancie.setGeometry(QtCore.QRect(170, 350, 211, 41))
        self.pregnancie.setObjectName("pregnancie")
        self.dmf = QtWidgets.QLineEdit(Form)
        self.dmf.setGeometry(QtCore.QRect(650, 530, 241, 41))
        self.dmf.setObjectName("dmf")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(490, 170, 111, 31))
        self.label_9.setObjectName("label_9")
        self.bmi = QtWidgets.QLineEdit(Form)
        self.bmi.setGeometry(QtCore.QRect(650, 270, 241, 41))
        self.bmi.setObjectName("bmi")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(490, 260, 81, 31))
        self.label_12.setObjectName("label_12")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(0, 560, 141, 71))
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(0, 370, 161, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(0, 470, 151, 41))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 270, 151, 41))
        self.label_2.setObjectName("label_2")
        self.hesapla = QtWidgets.QPushButton(Form)
        self.hesapla.setGeometry(QtCore.QRect(320, 710, 161, 71))
        self.hesapla.setObjectName("hesapla")
        self.yeni_kayit = QtWidgets.QPushButton(Form)
        self.yeni_kayit.setGeometry(QtCore.QRect(650, 710, 161, 71))
        self.yeni_kayit.setObjectName("yeni_kayit")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(0, 660, 161, 71))
        self.label_13.setObjectName("label_13")
        self.phone_number = QtWidgets.QLineEdit(Form)
        self.phone_number.setGeometry(QtCore.QRect(170, 640, 211, 41))
        self.phone_number.setText("")
        self.phone_number.setObjectName("phone_number")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(480, 640, 161, 71))
        self.label_14.setObjectName("label_14")
        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(650, 610, 241, 41))
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_3.setGeometry(QtCore.QRect(890, -20, 221, 871))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.name = QtWidgets.QLabel(Form)
        self.name.setGeometry(QtCore.QRect(0, 170, 101, 31))
        self.name.setObjectName("name")
        self.textBrowser_4 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_4.setGeometry(QtCore.QRect(0, 0, 171, 851))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_5.setGeometry(QtCore.QRect(480, 10, 171, 841))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_6.setGeometry(QtCore.QRect(0, 0, 1111, 111))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.temizle = QtWidgets.QPushButton(Form)
        self.temizle.setGeometry(QtCore.QRect(480, 710, 171, 71))
        self.temizle.setObjectName("temizle")
        self.hesapla.clicked.connect(self.show_popup)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.temizle.clicked.connect(self.temizlee)
        self.liste=[self.name_2,self.insulin,self.surname,self.bmi,self.pregnancie,self.skin_thickness,self.glucose,self.age,self.blood_pressure,self.dmf,self.phone_number,self.lineEdit_12]
    def temizlee(self):
        for i in self.liste:
            i.setText("")
    def show_popup(self):
            msg = QtWidgets.QMessageBox()
            msg.setWindowIcon(QtGui.QIcon("2.jpg"))
            if(self.name_2.text().isspace()==True or self.name_2.text()==""):

                msg.setWindowTitle("ERROR!")
                msg.setText("NAME kutucuğu boş!")
                msg.setIcon(QtWidgets.QMessageBox.Critical)
                x=msg.exec_()
            elif (self.insulin.text().isspace() == True or self.insulin.text() == ""):

                msg.setWindowTitle("ERROR!")
                msg.setText("INSULIN kutucuğu boş!")
                msg.setIcon(QtWidgets.QMessageBox.Critical)
                x = msg.exec_()
            elif (self.surname.text().isspace() == True or self.surname.text() == ""):

                msg.setWindowTitle("ERROR!")
                msg.setText("SURNAME kutucuğu boş!")

                msg.setIcon(QtWidgets.QMessageBox.Critical)
                x = msg.exec_()
            elif (self.bmi.text().isspace() == True or self.bmi.text() == ""):

                msg.setWindowTitle("ERROR!")
                msg.setText("BMI kutucuğu boş!")

                msg.setIcon(QtWidgets.QMessageBox.Critical)
                x = msg.exec_()
            elif (self.pregnancie.text().isspace() == True or self.pregnancie.text() == ""):

                msg.setWindowTitle("ERROR!")
                msg.setText("PREGNANCIE kutucuğu boş!")

                msg.setIcon(QtWidgets.QMessageBox.Critical)
                x = msg.exec_()
            elif (self.skin_thickness.text().isspace() == True or self.skin_thickness.text() == ""):

                msg.setWindowTitle("ERROR!")
                msg.setText("SKIN THICKNESS kutucuğu boş!")

                msg.setIcon(QtWidgets.QMessageBox.Critical)
                x = msg.exec_()
            elif (self.glucose.text().isspace() == True or self.glucose.text() == ""):

                msg.setWindowTitle("ERROR!")
                msg.setText("GLUCOSE kutucuğu boş!")

                msg.setIcon(QtWidgets.QMessageBox.Critical)
                x = msg.exec_()
            elif (self.age.text().isspace() == True or self.age.text() == ""):

                msg.setWindowTitle("ERROR!")
                msg.setText("AGE kutucuğu boş!")

                msg.setIcon(QtWidgets.QMessageBox.Critical)
                x = msg.exec_()
            elif (self.blood_pressure.text().isspace() == True or self.blood_pressure.text() == ""):

                msg.setWindowTitle("ERROR!")
                msg.setText("BLOOD PRESSURE kutucuğu boş!")

                msg.setIcon(QtWidgets.QMessageBox.Critical)
                x = msg.exec_()
            elif (self.dmf.text().isspace() == True or self.dmf.text() == ""):

                msg.setWindowTitle("ERROR!")
                msg.setText("DPF kutucuğu boş!")

                msg.setIcon(QtWidgets.QMessageBox.Critical)
                x = msg.exec_()
            elif (self.phone_number.text().isspace() == True or self.phone_number.text() == ""):

                msg.setWindowTitle("ERROR!")
                msg.setText("PHONE NUMBER kutucuğu boş!")

                msg.setIcon(QtWidgets.QMessageBox.Critical)
                x = msg.exec_()
            elif (self.lineEdit_12.text().isspace() == True or self.lineEdit_12.text() == ""):

                msg.setWindowTitle("ERROR!")
                msg.setText("MAIL kutucuğu boş!")

                msg.setIcon(QtWidgets.QMessageBox.Critical)
                x = msg.exec_()
            else:
                if(self.lineEdit_12.text().count("@")==1 and self.lineEdit_12.text().endswith(".com")==True):
                    msg.setText("malsın")
                    mail.mail(self.name_2.text(),self.surname.text(),self.insulin.text(),self.bmi.text()
                              ,self.pregnancie.text(),self.skin_thickness.text(),
                              self.glucose.text(),self.age.text(),self.blood_pressure.text()
                              ,self.dmf.text(),self.phone_number.text(),self.lineEdit_12.text(),1)
                    tahmin=mod.tahmin(self.pregnancie.text(),self.glucose.text(),self.blood_pressure.text(),self.skin_thickness.text(),
                               self.insulin.text(),self.bmi.text(),self.dmf.text(),self.age.text())
                    veriler.veri_ekle(self.name_2.text(),self.surname.text(),self.lineEdit_12.text(),
                                      self.pregnancie.text(),self.glucose.text(),self.blood_pressure.text(),
                                      self.skin_thickness.text(),self.insulin.text(),self.bmi.text(),
                                      self.dmf.text(),self.age.text(),tahmin)
                    if(tahmin==1):
                        msg.setText("Girmiş olduğunuz veriler doğrultusunda oranda diyabet belirtisi taşımaktadır.")
                        msg.setWindowTitle("Sonuç")
                    else:
                        msg.setText(
                            "Girmiş olduğunuz veriler doğrultusunda  diyabet belirtisi taşımamaktadır")
                        msg.setWindowTitle("Sonuç")
                else:
                    msg.setText("Lütfen geçerli bir mail adresi giriniz.")
                x = msg.exec_()
    def popup_button(self, i):
        print(i.text())
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\" bgcolor=\"#168e8c\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">SKIN</span></p><p><span style=\" font-size:14pt; font-weight:600;\">THICKNESS</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">AGE</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">DPF</span></p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body bgcolor=\"Limegreen\" ><p><span style=\" font-size:14pt; font-weight:600; color:#000000;\">INSULIN</span></p><p><br/></p></body></html>"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#000000;\">BMI<br/></span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#000000;\">BLOOD</span></p><p><span style=\" font-size:14pt; font-weight:600; color:#000000;\">PRESSURE</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">PREGNANCIE</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#000000;\">GLUCOSE</span></p><p><br/></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">SURNAME</span></p></body></html>"))
        self.hesapla.setText(_translate("Form", "HESAPLA"))
        self.yeni_kayit.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Yeni Kayıt</span></p></body></html>"))
        self.yeni_kayit.setText(_translate("Form", "YENİ KAYIT"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">PHONE</span></p><p><span style=\" font-size:14pt; font-weight:600;\">NUMBER</span></p><p><br/></p></body></html>"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">MAIL</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\" bgcolor=\"#168e8c\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">BMI = BODY MASS INDEX</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">DPF=DIABETES PEDIGREE FUNCTION</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600;\"><br /></p></body></html>"))
        self.name.setToolTip(_translate("Form", "<html><head/><body><p>dasdasdas</p><p><br/></p></body></html>"))
        self.name.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">DENEME</span></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\" bgcolor=\"#168e8c\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">NAME</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">SURNAME</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">PREGNANCIE</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#000000;\">GLUCOSE</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#000000;\">BLOOD</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#000000;\">PRESSURE</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">PHONE</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">NUMBER</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\"><br /><br /></span></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\" bgcolor=\"#168e8c\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#000000;\">INSULIN</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#000000;\">BMI<br /></span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">SKIN</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">THICKNESS</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">AGE</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">DPF</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">MAIL</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\"><br /><br /></span></p></body></html>"))
        self.textBrowser_6.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\" bgcolor=\"#2c3832\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">DİYABET PROJESİ</span></p></body></html>"))
        self.temizle.setText(_translate("Form", "TEMİZLE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
